---
title: "Title TBD"
bibliography: refs.bib
csl: jama.csl
always_allow_html: true
output: 
  officedown::rdocx_document:
    reference_docx: style_manuscript_times_new_roman.docx
    keep_md: true
---
```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, 
                      message = FALSE,
                      warning = FALSE,
                      dpi = 600, 
                      fig.width = 11, 
                      fig.height = 6)

rspec <- round_spec() |>
  round_using_magnitude(digits = c(2, 1, 0),
                        breaks = c(1, 10, Inf))

# save it to options:
names(rspec) <- paste('table.glue', names(rspec), sep = '.')
options(rspec)

# default is double space 
# single spacing for title page, abstract, captions
single_par <- fp_par(line_spacing=1)

abbrvs_paste <- function(strings){

  front <- 'Abbreviations'

  matter <- glue::glue_collapse(strings,
                                sep = '; ',
                                last = '; and ')

  paste(front, matter, sep = ': ')

}

abbrvs_write <- function(abbr){

  sorted <- abbr[sort(names(abbr))]

  strings <- map2_chr(names(sorted),
                      sorted,
                      paste, sep = ' = ')

  as_paragraph(abbrvs_paste(strings))

}


```

Byron C Jaeger, PhD^1^ 

^1^Biostatistics and Data Science, Wake Forest University School of Medicine, Winston-Salem, NC. `r single_par`


```{r data-prep, include=FALSE}

withr::with_dir(
  here::here(),
  code = {
    targets::tar_load(c(labels,
                        jhs_excluded, 
                        tbl_chars,
                        tbl_prevent_dist_cmbn))
  }
)

tbl_exclusions <- jhs_excluded$counts


```

\newpage


Table 1: Participant characteristics.

```{r}

tbl_chars %>% 
  footnote(
    i = 1, j = 1, 
    part = 'header',
    value = as_paragraph(
      "Table values are mean (standard deviation) or percent"
    ),
    ref_symbols = "1"
  ) %>% 
  add_footer_lines(
    value = abbrvs_write(labels$abbreviations[c("PREVENT", "CVD")])
  )

```

\newpage

Table 2: Distribution of PREVENT 10- and 30-year predicted risk for cardiovascular disease.

```{r}

tbl_dist_data <- tbl_prevent_dist_cmbn %>% 
  mutate(tbl_p = table_glue("{n} ({p*100})"),
         tbl_lv = table_glue("{lvmi_height} ({lvh_height * 100})"),
         tbl_htn = table_value(htn * 100)) %>% 
  select(group, matches("^cvd|^tbl")) %>% 
  pivot_longer(cols = starts_with("tbl")) %>% 
  split(.$name) %>% 
  map_dfr(
    ~ .x %>% 
      pivot_wider(names_from = group, 
                  values_from = value) %>% 
      select(-name),
    .id = 'stat'
  ) %>% 
  mutate(
    stat = factor(
      stat, 
      levels = c('tbl_p',
                 'tbl_htn', 
                 'tbl_lv'),
      labels = c("N (%) of participants",
                 "% with hypertension at visit 2 or visit 3",
                 "LV mass mean (% with LV hypertrophy)  at visit 3")
    )
  ) %>% 
  arrange(stat)

tbl_dist_data %>%
  as_grouped_data(groups = 'stat') %>% 
  as_flextable(hide_grouplabel = TRUE) %>% 
  theme_box() %>% 
  bg(i =~ !is.na(stat), bg = 'grey90') %>% 
  add_header_row(values = c("PREVENT CVD risk", 
                            "Blood pressure category"),
                 colwidths = c(2, 4)) %>% 
  merge_v(j = ~cvd_prevent_bnry_10, part = 'body') %>% 
  align(align = 'center', part = 'all') %>% 
  align(j = 1, align = 'left', part = 'all') %>%
  set_header_labels(
    cvd_prevent_bnry_10 = "10-year",
    cvd_prevent_cat_30 = "30-year",
    overall = "Overall",
    norm = labels$levels$bp_cat['norm'],
    elevated = labels$levels$bp_cat['elevated'],
    stage_1 = labels$levels$bp_cat['stage_1']
  ) %>% 
  width(width = 1.2)

```


\newpage

Table S1: Exclusions

```{r tbl_exclusions}

tbl_exclusions %>% 
  select(label, n) %>% 
  flextable() %>% 
  theme_box() %>% 
  width(j = 1, width = 4) %>% 
  width(j = 2, width = 1.5) %>% 
  set_header_labels(label = "Inclusion criteria",
                    n = "No. of participants")

```
